paths:
  /deals/{dealId}/parameters:
    post:
      summary: Set earn-out parameters for a deal
      description: |
        **Purpose**: Configure earn-out periods, KPI types, thresholds, and calculation formulas for a deal

        **Business Logic**:
        - Defines periods (time ranges) for earn-out tracking
        - Sets KPI types and thresholds for each period
        - Configures payout calculation formulas
        - Generates human-readable summary of earn-out terms
        - Creates transaction to lock parameters on-chain (irreversible)

        **Sui Integration**:
        - Writes: Calls `earnout::set_parameters()` Move function
        - Transaction: Returns unsigned transaction for user to sign
        - State: Parameters are locked after transaction is signed
        - Events: Emits `ParametersLocked` event with dealId
        - Gas: Estimated ~2,000,000 MIST (varies with number of periods)

        **Critical Notes**:
        - Parameters can only be set ONCE per deal (or modified before locking)
        - After locking, parameters are immutable on-chain
        - Frontend must show clear warning before user signs transaction
        - Formulas are encoded as Move structs and stored on-chain

        **Access Control**:
        - Role: Buyer only
        - Verification: User address must match deal.buyer
        - Status: Deal must be in "draft" status
      operationId: setParameters
      tags:
        - Parameters
      parameters:
        - name: X-Sui-Address
          in: header
          required: true
          schema:
            type: string
            pattern: '^0x[a-fA-F0-9]{64}$'
          description: Sui wallet address (must be buyer)
        - name: X-Sui-Signature
          in: header
          required: true
          schema:
            type: string
          description: Signature proving ownership
        - name: dealId
          in: path
          required: true
          schema:
            type: string
            pattern: '^0x[a-fA-F0-9]{64}$'
          description: Deal ID
          example: "0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../schemas/period.yaml#/components/schemas/SetParametersRequest'
            example:
              periods:
                - name: "2026 Fiscal Year"
                  startDate: "2026-01-01"
                  endDate: "2026-12-31"
                  kpiTypes:
                    - type: "revenue"
                      threshold: 10000000
                      unit: "USD"
                      description: "Total revenue recognized in FY2026"
                  formula:
                    type: "linear"
                    maxPayout: 5000000
                    parameters:
                      minKPI: 10000000
                      maxKPI: 15000000
                      minPayout: 0
                      maxPayout: 5000000
                    description: "Linear payout from $0 to $5M as revenue grows from $10M to $15M"
                - name: "2027 Fiscal Year"
                  startDate: "2027-01-01"
                  endDate: "2027-12-31"
                  kpiTypes:
                    - type: "ebitda"
                      threshold: 8000000
                      unit: "USD"
                      description: "EBITDA for FY2027"
                  formula:
                    type: "stepped"
                    maxPayout: 3000000
                    parameters:
                      steps:
                        - threshold: 8000000
                          payout: 1000000
                        - threshold: 10000000
                          payout: 2000000
                        - threshold: 12000000
                          payout: 3000000
      responses:
        '200':
          description: Parameters validated and transaction ready
          content:
            application/json:
              schema:
                $ref: '../schemas/period.yaml#/components/schemas/SetParametersResponse'
              example:
                parameters:
                  periods:
                    - periodId: "period_2026"
                      name: "2026 Fiscal Year"
                      startDate: "2026-01-01"
                      endDate: "2026-12-31"
                      kpiTypes:
                        - type: "revenue"
                          threshold: 10000000
                          unit: "USD"
                      formula:
                        type: "linear"
                        maxPayout: 5000000
                      status: "pending"
                summary: |
                  Earn-out Agreement Summary:

                  Period 1: 2026-01-01 to 2026-12-31 (2026 Fiscal Year)
                  - KPI: Revenue (Threshold: $10,000,000 USD)
                  - Max Payout: $5,000,000 USD
                  - Formula: Linear from $0 to $5M as revenue grows from $10M to $15M

                  Period 2: 2027-01-01 to 2027-12-31 (2027 Fiscal Year)
                  - KPI: EBITDA (Threshold: $8,000,000 USD)
                  - Max Payout: $3,000,000 USD
                  - Formula: Stepped - $1M at $8M, $2M at $10M, $3M at $12M

                  Total Maximum Payout: $8,000,000 USD
                transaction:
                  txBytes: "AAACAAgA..."
                  description: "Lock earn-out parameters for deal"
                  warning: "WARNING: Once locked, these parameters cannot be changed without mutual agreement"
                  estimatedGas: 2000000
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '../schemas/errors.yaml#/components/schemas/ValidationError'
              examples:
                invalidDateRange:
                  value:
                    error: "ValidationError"
                    message: "Invalid period date ranges"
                    statusCode: 400
                    validationErrors:
                      - field: "periods[0].endDate"
                        message: "End date must be after start date"
                        constraint: "endDate > startDate"
                overlappingPeriods:
                  value:
                    error: "ValidationError"
                    message: "Period date ranges overlap"
                    statusCode: 400
                    details:
                      period1: "2026-01-01 to 2026-12-31"
                      period2: "2026-06-01 to 2027-06-30"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '../schemas/errors.yaml#/components/schemas/UnauthorizedError'
        '403':
          description: Forbidden - Only buyer can set parameters
          content:
            application/json:
              schema:
                $ref: '../schemas/errors.yaml#/components/schemas/ForbiddenError'
        '404':
          description: Deal not found
          content:
            application/json:
              schema:
                $ref: '../schemas/errors.yaml#/components/schemas/NotFoundError'
        '409':
          description: Conflict - Parameters already locked
          content:
            application/json:
              schema:
                $ref: '../schemas/errors.yaml#/components/schemas/ConflictError'
              example:
                error: "ConflictError"
                message: "Parameters already locked"
                statusCode: 409
                conflictReason: "Parameters were locked on 2025-11-20T10:00:00Z"
                details:
                  lockedAt: "2025-11-20T10:00:00Z"

    get:
      summary: Get current earn-out parameters
      description: |
        **Purpose**: Retrieve configured earn-out parameters for a deal

        **Business Logic**:
        - Fetches parameters from Sui blockchain
        - Generates human-readable summary
        - Returns lock status (whether parameters are immutable)

        **Sui Integration**:
        - Reads: Fetches Deal.periods from on-chain
        - Reads: Fetches parameter lock status
        - Caching: Cached until lock status changes

        **Access Control**:
        - Role: All deal participants (buyer, seller, auditor)
        - Verification: User must be a participant in this deal
      operationId: getParameters
      tags:
        - Parameters
      parameters:
        - name: X-Sui-Address
          in: header
          required: true
          schema:
            type: string
            pattern: '^0x[a-fA-F0-9]{64}$'
        - name: X-Sui-Signature
          in: header
          required: true
          schema:
            type: string
        - name: dealId
          in: path
          required: true
          schema:
            type: string
            pattern: '^0x[a-fA-F0-9]{64}$'
      responses:
        '200':
          description: Successfully retrieved parameters
          content:
            application/json:
              schema:
                $ref: '../schemas/period.yaml#/components/schemas/GetParametersResponse'
              example:
                dealId: "0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef"
                periods:
                  - periodId: "period_2026"
                    name: "2026 Fiscal Year"
                    startDate: "2026-01-01"
                    endDate: "2026-12-31"
                    kpiTypes:
                      - type: "revenue"
                        threshold: 10000000
                        unit: "USD"
                    formula:
                      type: "linear"
                      maxPayout: 5000000
                    status: "data_collection"
                locked: true
                lockedAt: "2025-11-20T10:00:00Z"
                summary: "Period 1 (2026): Revenue ≥ $10M → up to $5M payout (linear)"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '../schemas/errors.yaml#/components/schemas/UnauthorizedError'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '../schemas/errors.yaml#/components/schemas/ForbiddenError'
        '404':
          description: Deal not found or parameters not set
          content:
            application/json:
              schema:
                $ref: '../schemas/errors.yaml#/components/schemas/NotFoundError'
